# Generated by Django 6.0.2 on 2026-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_check', '0002_alter_vehicle_current_mileage_alter_vehicle_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='chasis_no',
        ),
        migrations.AddField(
            model_name='txn',
            name='current_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='txn',
            name='kms_driven',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='average_mileage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
