# Generated by Django 6.0.2 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_check', '0003_remove_vehicle_chasis_no_txn_current_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='money_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
