# Generated by Django 6.0.2 on 2026-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_check', '0005_alter_txn_current_mileage_alter_txn_fuel_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn',
            name='txn_date',
            field=models.DateField(blank=True, help_text='Date of the transaction (optional, defaults to today)', null=True),
        ),
    ]
