# Generated by Django 6.0.2 on 2026-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_check', '0006_txn_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='total_kms_driven',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
