# Generated by Django 6.0.2 on 2026-05-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_check", "0007_alter_vehicle_total_kms_driven"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="txn",
            name="price_per_liter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-calculated: amount / fuel_qty",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("oil_change", "Oil Change"),
                            ("regular_service", "Regular Service"),
                            ("brake_service", "Brake Service"),
                            ("tire_change", "Tire Change"),
                            ("battery", "Battery"),
                            ("insurance", "Insurance"),
                            ("puc", "PUC Check"),
                            ("road_tax", "Road Tax"),
                            ("other", "Other"),
                        ],
                        default="regular_service",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "odometer_reading",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "garage_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="fuel_check.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date"],
            },
        ),
    ]
